🎨 Add comments in Layouts.tsx, Layout.ts, Root.tsx, classic.blocks/_index.tsx, Unit.ts, Config.tsx, Format.tsx
Jerrylum/path.jerryio pull request #36
Opened 2024-05-27 12:51 UTC by crapper

2024-05-27 21:27 UTC, Jerrylum requested changes
Everything is good, including the PR title, please address the following feedbacks

2024-05-27 21:27 UTC, Jerrylum commented on src/format/Format.tsx
> +   * A dispose function triggered when MainApp changes format
Use the following
```
Unregisters the format from the application.

This should clean up and remove any hooks, event listeners, or UI components that were added during the registration process.

The `unregister` function should be the last function to call on the format. After it is called, the format is expected to be detached from the application. This is triggered when MainApp changes format.
```

2024-05-27 21:27 UTC, Jerrylum commented on src/format/Format.tsx
> +    // From v0.8.0 to current app version
Nice one

2024-05-27 21:27 UTC, Jerrylum commented on src/app/classic.blocks/_index.tsx
I think you can remove this comment

2024-05-29 15:29 UTC, crapper commented on src/app/classic.blocks/_index.tsx
Removed.

2024-05-29 15:29 UTC, crapper commented on src/format/Format.tsx
> +   * A dispose function triggered when MainApp changes format
Updated, thank you!

2024-05-29 15:30 UTC, crapper commented on src/format/Format.tsx
> +   * A initialize function triggered when MainApp changes format
Updated, thank you!

2024-05-29 15:31 UTC, crapper commented on src/format/Format.tsx
> +   * Create a new instance of this format
Updated, thank you!

2024-05-29 15:31 UTC, crapper commented on src/format/Format.tsx
> +   * Create a path instance with the given segments
Updated, thank you!

2024-05-29 15:31 UTC, crapper commented on src/format/Format.tsx
> +   * Get the points along a path at a uniform density
Updated, thank you!

2024-05-29 15:33 UTC, crapper commented on src/format/Format.tsx
> +   * @param app The MainApp component
Double-checked; I believe here is the only place I misused the term instance vs. component. Thank you very much!!!

2024-05-31 00:59 UTC, merged